# docker-compose.yml - Single project configuration
# Change PORT environment variable for different projects
version: '3.8'

services:
  website:
    build: .
    container_name: ${PROJECT_NAME:-bardo-website}
    ports:
      - "${PORT:-8080}:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - PROJECT_NAME=${PROJECT_NAME:-bardo-website}
      - PORT=${PORT:-8080} 