version: '3.8'

services:
  bardo-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30002:3000"  # Port cho dự án bardo
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    container_name: bardo-website
    networks:
      - reward-network
      - tunnel-bridge
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Uncomment the following lines if you want to use environment variables
    env_file:
      #- .env.local
      - .env.production

networks:
  reward-network:
    driver: bridge
  tunnel-bridge:
    external: true
